export const CAR_MODELS = [
  'Audi RS3',
  'Audi RS4',
  'Audi RS5',
  'Audi RS6',
  'Audi RS7',
  'Audi RS Q3',
  'Audi TT RS',
  'Audi R8',
  'Audi S3',
  'Audi S4',
  'Bentley Continental GT',
  'Bentley Flying Spur',
  'Bentley Bentayga',
  'Bentley Mulsanne',
  'Bentley Continental GT Convertible',
  'Bentley Bentayga Hybrid',
  'Bentley Continental GT Speed',
  'Bentley Bentayga Speed',
  'Bentley Continental GT Mulliner',
  'Bentley Flying Spur Mulliner',
  'BMW M2',
  'BMW M3',
  'BMW M4',
  'BMW M5',
  'BMW M6',
  'BMW M8',
  'BMW X3 M',
  'BMW X4 M',
  'BMW X5 M',
  'BMW X6 M',
  'Ford Mustang',
  'Ford Mustang Mach-E GT',
  'Ford Mustang Shelby GT350',
  'Ford Mustang Shelby GT500',
  'Ford Focus RS',
  'Ford Fiesta ST',
  'Ford F-150 Raptor',
  'Ford Ranger Raptor',
  'Ford GT',
  'Ford Edge ST',
  'Honda Civic Type R',
  'Honda NSX',
  'Honda S2000',
  'Honda Integra Type R',
  'Honda Prelude',
  'Honda CR-Z',
  'Honda Beat',
  'Honda Fit/Jazz RS',
  'Honda Accord Euro-R',
  'Honda CR-X',
  'Mercedes-AMG A 45',
  'Mercedes-AMG C 63',
  'Mercedes-AMG E 63',
  'Mercedes-AMG GT',
  'Mercedes-AMG GT 4-Door Coupe',
  'Mercedes-AMG CLA 45',
  'Mercedes-AMG GLA 45',
  'Mercedes-AMG G 63',
  'Mercedes-AMG S 63',
  'Mercedes-AMG SL 63',
  'Mitsubishi Lancer Evolution',
  'Mitsubishi Eclipse',
  'Mitsubishi 3000GT',
  'Mitsubishi Mirage R5',
  'Mitsubishi Colt Ralliart',
  'Mitsubishi Galant VR-4',
  'Mitsubishi GTO',
  'Mitsubishi Outlander GT',
  'Mitsubishi ASX Ralliart',
  'Mitsubishi Lancer Ralliart',
  'Nissan GT-R',
  'Nissan 370Z',
  'Nissan 350Z',
  'Nissan Silvia',
  'Nissan Skyline GT-R',
  'Nissan Fairlady Z',
  'Nissan 300ZX',
  'Nissan Pulsar GTI-R',
  'Nissan Sentra SE-R Spec V',
  'Nissan Juke Nismo RS',
  'Porsche 911',
  'Porsche 718 Cayman',
  'Porsche 718 Boxster',
  'Porsche Cayman GT4',
  'Porsche Boxster Spyder',
  'Porsche 911 Turbo',
  'Porsche 911 GT3',
  'Porsche Taycan Turbo S',
  'Porsche Panamera Turbo S',
  'Porsche Macan Turbo',
  'Subaru WRX STI',
  'Subaru BRZ',
  'Subaru Impreza WRX',
  'Subaru Legacy GT Spec.B',
  'Subaru XV Crosstrek Hybrid',
  'Subaru Forester XT',
  'Subaru Levorg STI Sport',
  'Subaru Outback XT',
  'Subaru Baja Turbo',
  'Subaru Tribeca 3.6R',
  'Tesla Model S',
  'Tesla Model 3',
  'Tesla Model X',
  'Tesla Model Y',
  'Tesla Roadster',
  'Tesla Semi',
  'Tesla Cybertruck',
  'Tesla Model S Plaid',
  'Tesla Model 3 Performance',
  'Tesla Model X Plaid',
  'Toyota Supra',
  'Toyota 86',
  'Toyota MR2',
  'Toyota Celica',
  'Toyota Corolla GT-S',
  'Toyota Celica GT-Four',
  'Toyota Camry TRD',
  'Toyota Yaris GR',
  'Toyota Prius Prime',
  'Toyota C-HR GR Sport',
]
